/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtualizarResultadosRouteImport } from './routes/atualizar-resultados'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MinhaPerformanceRouteImport } from './routes/minha-performance'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarResultadosRoute = AtualizarResultadosRouteImport.update({
  id: '/atualizar-resultados',
  path: '/atualizar-resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaPerformanceRoute = MinhaPerformanceRouteImport.update({
  id: '/minha-performance',
  path: '/minha-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizar-resultados': typeof AtualizarResultadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/metas': typeof MetasRoute
  '/minha-performance': typeof MinhaPerformanceRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar-resultados': typeof AtualizarResultadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/metas': typeof MetasRoute
  '/minha-performance': typeof MinhaPerformanceRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atualizar-resultados': typeof AtualizarResultadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/metas': typeof MetasRoute
  '/minha-performance': typeof MinhaPerformanceRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizar-resultados'
    | '/configuracoes'
    | '/equipe'
    | '/metas'
    | '/minha-performance'
    | '/relatorios'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar-resultados'
    | '/configuracoes'
    | '/equipe'
    | '/metas'
    | '/minha-performance'
    | '/relatorios'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/atualizar-resultados'
    | '/configuracoes'
    | '/equipe'
    | '/metas'
    | '/minha-performance'
    | '/relatorios'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtualizarResultadosRoute: typeof AtualizarResultadosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EquipeRoute: typeof EquipeRoute
  MetasRoute: typeof MetasRoute
  MinhaPerformanceRoute: typeof MinhaPerformanceRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-resultados': {
      id: '/atualizar-resultados'
      path: '/atualizar-resultados'
      fullPath: '/atualizar-resultados'
      preLoaderRoute: typeof AtualizarResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-performance': {
      id: '/minha-performance'
      path: '/minha-performance'
      fullPath: '/minha-performance'
      preLoaderRoute: typeof MinhaPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtualizarResultadosRoute: AtualizarResultadosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EquipeRoute: EquipeRoute,
  MetasRoute: MetasRoute,
  MinhaPerformanceRoute: MinhaPerformanceRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
